### ISSUE TITLE
Any package or CRA integration for Next.js

### ISSUE THREAD

**Issue by 5ervant** [brunolemos/react-native-web-monorepo#14]
Do you think it's possible to integrate *"packages/web/"* into [/zeit/next.js/tree/master/examples/with-react-native-web][1] in case we need a SSR for other web pages, or `react-native-web` navigation isn't a good fit for Next.js?

Any guide how can I setup [/zeit/next.js/tree/master/examples/with-react-native-web][1] to be one of the packages of this monorepo? Thanks!

  [1]: https://github.com/zeit/next.js/tree/master/examples/with-react-native-web

**Comment by brunolemos** [comment]
Hi, I’ve never used Next.js, but they have an official example so I believe it should work fine!

**Comment by 5ervant** [comment]
@luizcarlospedrosogomes I suggest using https://expo.io/ if you're looking to have a multi-platform application.

**Comment by 5ervant** [comment]
@luizcarlospedrosogomes I have a Next.js application with Expo for web.
Come and see it at: https://techintel.github.io

I didn't open source the code yet.
Next.js with Expo is quite challenging because you need to implement both Next.js side and `react-native` side.
I believe creating CRA and `react-native` platform app is pretty straight forward with Expo.

Here are the static HTML exported files: https://github.com/techintel/techintel.github.io/

**Comment by kenchoong** [comment]
For next.js, you need to transpile your code in order next.js can use the component outside the project directory. In this case, do as follow: 

First, install this package in your `root` directory

`yarn add next-transpile-modules` 

then in your `next.config.js`

```
const withTM = require("next-transpile-modules")(["components/src"]);

module.exports = withTM({
  webpack: (config) => {
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      // Transform all direct `react-native` imports to `react-native-web`
      'react-native$': 'react-native-web',
    };
    config.resolve.extensions = [
      '.web.js',
      '.web.ts',
      '.web.tsx',
      ...config.resolve.extensions,
    ];
    return config
  },
});


```

then in your page `example.js` you can use the component like this: 

```
import React from 'react'
import MyExampleComponent from 'components/src/TestComponent'

export default function Example() {
    return(
        <MyExampleComponent/>
    )
}
```

**Comment by luizcarlospedrosogomes** [comment]
the question is: is a complex application like an ecomerce worth using RNW and in monorepo? Where could I ask this question?
