### ISSUE TITLE
How to run the app

### ISSUE THREAD

**Issue by vegtelenseg** [brunolemos/react-native-web-monorepo#2]
Hello,

Thank for this work.

I am struggling running the application. I followed your steps to the letter, but running ```yarn workspace mobile start``` does not run the app but the bundler. It is not very clear to me how I would get to run the app in either platform.
Please help?

Thank you

**Comment by vegtelenseg** [comment]
Hello,

I have figured this out. Closing this.

Thanks

**Comment by komaljain** [comment]
Can you please post the solution here? I am not able to run the application

**Comment by kenchoong** [comment]
@komaljain #49 you can look at this solution, you need to port forwarding to 8081..you can do this in `chrome://inspect/devices#devices` in browswer,then can run on real device ady
