### ISSUE TITLE
Will React Native version .60 cause problems

### ISSUE THREAD

**Issue by matt-eaton** [brunolemos/react-native-web-monorepo#20]
Hi, @brunolemos thx for the repo and your tutorial. I was really struggling with this setup until I came across your article. Quick question I see in your repo is using React Native 0.61, but react-native-web only supports React Native 0.55. Wondering if that will cause any issues down the line. 

Looks like RNW has an issue to support 0.60 https://github.com/necolas/react-native-web/issues/1172#issue-379958228

Thanks

**Comment by brunolemos** [comment]
You can use it, but react-native-web still have the 0.55 code, not the updated code.
It should be fine, except for some packages that are being removed from the react-native core (like AsyncStorage), so you need to use the community package and check if they already have web support.

If they don't have web support, then maybe you could do something like this:

`index.native.js` -> `export { Package } from '@react-native-community/package`
`index.web.js` -> `export { Package } from 'react-native'`
