### ISSUE TITLE
how to port to expo

### ISSUE THREAD

**Issue by wuichen** [brunolemos/react-native-web-monorepo#23]
I would like to modify a bit to make it work with expo. are there anything in mind that should be take care?

**Comment by brunolemos** [comment]
Hi, I've never used Expo, so I'm not able to help you. 

Maybe check other articles and repositories:
- https://medium.com/hy-vee-engineering/creating-a-monorepo-with-lerna-yarn-workspaces-cf163908965d
- https://github.com/Fried-Chicken/expo-monorepo

**Comment by wuichen** [comment]
Thanks! Btw awesome project
