### ISSUE TITLE
How to fix auto-linking on Android

### ISSUE THREAD

**Issue by marnusw** [brunolemos/react-native-web-monorepo#24]
Following the instructions for updating the RN CLI in the [`auto-linking docs`](https://github.com/react-native-community/cli#updating-the-cli) as recommended in [react-native-community/cli#537-comment](https://github.com/react-native-community/cli/issues/537#issuecomment-513232197) seems to be sufficient to fix auto-linking for Android!

**Comment by brunolemos** [comment]
Upgraded react-native and the cli, should be fixed now!
