### ISSUE TITLE
Tutorial change

### ISSUE THREAD

**Issue by gabrielbull** [brunolemos/react-native-web-monorepo#32]
>This is a workaround that may get fixed at any time. You may or may not need to have react-native dependency in the root package.json

To:

>This is a workaround that may get fixed at any time. You need to have react-native dependency in the root package.json, otherwise you will not be able to bundle the JS.

**Comment by brunolemos** [comment]
Is that workaround still necessary after their latest release? Maybe it’s not anymore

**Comment by gabrielbull** [comment]
It is to build the js bundle. Everything works otherwise. It seems react native cli checks the package.json to find the dependencies, it only needs react-native, if it's not there, it does not work.

**Comment by brunolemos** [comment]
Updated the article but if you can please open an issue in the cli repository
