### ISSUE TITLE
Compatibility with CSS files and react-native-css-transformer

### ISSUE THREAD

**Issue by agusvazquez** [brunolemos/react-native-web-monorepo#36]
Hello Bruno! I wanted to thank you for this guide, it really helped me a lot on my development.

Although I'm facing an issue here.

I've successfully set up android, iOS and web, everything works just fine during development. We had to add this lib so CSS files that are being used on web do not impact on mobile.

We were getting the following error that got fixed on development.

`error Unable to resolve module 'flexboxgrid2/flexboxgrid2.css' from 'node_modules/react-flexbox-grid/lib/classNames.js': flexboxgrid2/flexboxgrid2.css could not be found within the project.`

https://www.npmjs.com/package/react-native-css-transformer

The issue I'm facing now is when I build the app into release mode, using gradle bundleRelease / assembleRelease for android, and Build->Archive for iOS it breaks with the same error as above.

But on development everything is working fine!

I have a feeling that babel.config.js and metro.config.js files are not being read.

Any thoughts?

Thanks!! :)

**Comment by brunolemos** [comment]
Hi,

When using `react-native-web` there shouldn't be any `.css` file in the project.
All styles should be done in JavaScript by using `StyleSheet` or other `css-in-js` solution.

If you DO need to have a CSS, maybe only import it on `.web.js` files, doesn't that work?

**Comment by agusvazquez** [comment]
Hey Bruno! Thanks for your quick response and for taking the time to help me.

Well, right now the project has a lot of .SCSS files (I'm mobile developer and that doesn't depend on me either).

What I noticed is that the web team is using the following lib. 

https://www.npmjs.com/package/react-flexbox-grid

This lib internally uses `flexboxgrid2/flexboxgrid2.css` and that is the reason for the error.

I will try renaming to .web.js files and see if that helps. But I don't know what to do with that lib since it is used a lot along the web project.

Thanks!!
