### ISSUE TITLE
How should DeviceEventEmitter be used?

### ISSUE THREAD

**Issue by MrLaibin** [brunolemos/react-native-web-monorepo#4]
My project is a hybrid project that contains both native and react-native code.
There are some DeviceEventEmitter in the project. I want to use react-native-web, what should I do?

**Comment by brunolemos** [comment]
Hi, 

Maybe you will need to create a index.native.js that uses DeviceEventEmitter and a index.web.js that uses another emitter lib.
Here's an example of this with another library: https://github.com/devhubapp/devhub/tree/master/packages/components/src/libs/bugsnag


Also check this thread for more help: https://github.com/necolas/react-native-web/issues/1115
