### ISSUE TITLE
question: web can't find module 'react-native/Libraries/NewAppScreen' ?

### ISSUE THREAD

**Issue by connectdotz** [brunolemos/react-native-web-monorepo#40]
First of all, thanks for creating this demo and a wonderful blog 🙏 . 

I created a brand new project with react-native@0.61.5, following your instructions and this repo, I was able to get mobile running but the web failed with this error:
```
Failed to compile.

../components/src/App.tsx
Module not found: Can't resolve 'react-native/Libraries/NewAppScreen'
```
I noticed that you actually created a separate `AppHeader.tsx` and `AppHeader.web.tsx` in the `components/src`, wondering if you encountered the same problem thus the workaround and if you can shed some light on the actual root cause?

Thanks.

**Comment by brunolemos** [comment]
Hi, react-native-web doesn’t include `NewAppScreen`, so you can’t have a code that reference it on web.

**Comment by connectdotz** [comment]
hmm... does `react-native/Libraries/NewAppScreen` get alias to `react-native-web/Libraries/NewAppScreen`?

**Comment by brunolemos** [comment]
Depends on your webpack config. If you are using create-react-app, all your react-native will be aliased to react-native-web. I guess you can override the alias for some paths.
