### ISSUE TITLE
Could not find a declaration file for module 'react-navigation'

### ISSUE THREAD

**Issue by bruxalldev** [brunolemos/react-native-web-monorepo#43]
Hi I'm running into declartion file issues with npm/yarn imports - is there a way to avoid this or do I have to manually create these for them to work?

**Comment by brunolemos** [comment]
Are you sure this error is related to this repository? This project doesn’t contain react-navigation.

Sounds like you need to install @types/react-navigation check your TypeScript config. Or upgrade to react-navigation v5.

**Comment by bruxalldev** [comment]
Ahhh okay thanks - I've just found this as well which works but feels a bit 'dirty' I added  "noImplicitAny": false, to the tsconfig.json. Will have a look at react-navigation v5 now thanks again
