### ISSUE TITLE
react native elements

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [brunolemos/react-native-web-monorepo#54]
error Avatar.js: Unexpected token

how configure react native elements in the file  config-overrides.js?

**Comment by brunolemos** [comment]
Hi, I've never used this library, but this error means you need to transpile the code.

You'll need to add their node_modules path to `config-overrides.js` like this:

```diff
 const appIncludes = [
   resolveApp('src'),
   resolveApp('../core/src'),
   resolveApp('../components/src'),
+  resolveApp('../../node_modules/react-native-elements/'),
+  resolveApp('../../node_modules/react-native-vector-icons/'),
+  resolveApp('../../node_modules/react-native-ratings/'),
]
```

Also check their docs about web usage to see if there's any other step: https://react-native-elements.github.io/react-native-elements/docs/web_usage.html
