### ISSUE TITLE
can't integrate native-base 

### ISSUE THREAD

**Issue by ebrahimhassan121** [brunolemos/react-native-web-monorepo#6]
`const fs = require('fs')
const path = require('path')
const webpack = require('webpack')

const appDirectory = fs.realpathSync(process.cwd())
const resolveApp = relativePath => path.resolve(appDirectory, relativePath)

// our packages that will now be included in the CRA build step
const appIncludes = [
  resolveApp('src'),
  resolveApp('../components/src'),
  resolveApp('node_modules/native-base-shoutem-theme'),
  resolveApp('node_modules/react-navigation'),
  resolveApp('node_modules/react-native-easy-grid'),
  resolveApp('node_modules/react-native-drawer'),
  resolveApp('node_modules/react-native-safe-area-view'),
  resolveApp('node_modules/react-native-vector-icons'),
  resolveApp('node_modules/react-native-keyboard-aware-scroll-view'),
  resolveApp('node_modules/react-native-web'),
  resolveApp('node_modules/react-native-tab-view'),
  resolveApp('node_modules/static-container'),
]
module.exports = function override(config, env) {
  // allow importing from outside of src folder
  config.resolve.plugins = config.resolve.plugins.filter(
    plugin => plugin.constructor.name !== 'ModuleScopePlugin'
  )
  config.module.rules[0].include = appIncludes
  config.module.rules[1] = null
  config.module.rules[2].oneOf[1].include = appIncludes
  config.module.rules[2].oneOf[1].options.plugins = [
    require.resolve('@babel/plugin-proposal-class-properties'),
    require.resolve('babel-plugin-react-native-web'),

  ].concat(config.module.rules[2].oneOf[1].options.plugins)
  config.module.rules = config.module.rules.filter(Boolean)
  config.plugins.push(
    new webpack.DefinePlugin({ __DEV__: env !== 'production' }),a
  )
  return config
}

`

**Comment by brunolemos** [comment]
Hopefully you managed to make it work!
If not, you can follow this guide and open an issue on native-base: https://docs.nativebase.io/docs/GetStarted.html#Setup_with_Web

Closing as this is out of scope of the tutorial.
