### ISSUE TITLE
How to add third party sources repo-wide?

### ISSUE THREAD

**Issue by Pra3t0r5** [brunolemos/react-native-web-monorepo#61]
I'm trying to use `react-native-vector-icons`, after adding it to `web`, `mobile` and `commons` (your `components` package) and appending:
```gradle
apply from: "../../../../node_modules/react-native-vector-icons/fonts.gradle"
```
to the `mobile/android/app/build.gradle`, accordingly to the documentation, the project seems to not care and not load any icons. Instead it shows the "broken resource" crossed box.
This is my code:
```javascript
import * as React from 'react';
import { View, Text } from 'react-native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import Icon from 'react-native-vector-icons/Ionicons';

import { Home } from '../../src/components/organisms/Home';

const Tab = createBottomTabNavigator();

const dummyTab = () => {
    return (
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
            <Text>Test</Text>
        </View>
    );
}

export default function Tabs() {
    return (
        <Tab.Navigator
            initialRouteName="Inicio"
            backBehavior="history"
            tabBarOptions={{
                activeTintColor: 'rgb(29, 161, 242)',
                inactiveTintColor: 'rgb(136, 153, 166)',
            }}
            screenOptions={({ route }) => ({
                tabBarIcon: ({
                    focused, color, size
                }) => {
                    let iconName;
                    switch (route.name) {
                        case 'Inicio':
                            iconName = focused ? 'ios-home' : 'ios-home-outline';
                            break;
                        case 'Explorar':
                            iconName = focused ? 'ios-search' : 'ios-search-outline';
                            break;
                        case 'Notificaciones':
                            iconName = focused ? 'ios-notifications' : 'ios-notifications-outline';
                            break;
                        case 'Chats':
                            iconName = focused ? 'ios-chatbubbles' : 'ios-chatbubbles-outline';
                            break;
                    }
                    return <Icon name={iconName} size={size} color={color} />;
                }
            })}>
            <Tab.Screen name="Inicio" component={Home}/>
            <Tab.Screen name="Explorar" component={dummyTab} />
            <Tab.Screen name="Notificaciones" component={dummyTab} />
            <Tab.Screen name="Chats" component={dummyTab} />
        </Tab.Navigator>
    )
}
```

**Comment by hosseinmd** [comment]
I have imported fonts this way
```
project.ext.vectoricons = [
    iconFontNames: ['MaterrialIcons.ttf'] // Name of the font files you want to copy
]

apply from: "../../../../node_modules/react-native-vector-icons/fonts.gradle"
```

**Comment by Pra3t0r5** [comment]
I forgot to say that i've already tried that syntax too, here is the error i get with it:
```
Failed to compile
/home/praetors/Projects/node/proyectoSembrar/node_modules/react-native-vector-icons/lib/create-icon-set.js
SyntaxError: /home/praetors/Projects/node/proyectoSembrar/node_modules/react-native-vector-icons/lib/create-icon-set.js: Support for the experimental syntax 'classProperties' isn't currently enabled (43:10):

  41 | 
  42 |   class Icon extends PureComponent {
> 43 |     root = null;
     |          ^
  44 | 
  45 |     static propTypes = {
  46 |       allowFontScaling: PropTypes.bool,

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
This error occurred during the build time and cannot be dismissed.
```
And this is the variant i'm using:
```gradle
project.ext.vectoricons = [
    iconFontNames: ['Ionicons.ttf']
]
apply from: "../../../../node_modules/react-native-vector-icons/fonts.gradle"
```

Should i open Android Studio and sync it  after each new import?

**Comment by Pra3t0r5** [comment]
## Continuation of EDIT 2 (see previous comment)

### Workaround
Okay, I've managed to compile both web and mobile projects without errors by using a fork of `react-native-vector-icons` called `@ovaeasy/react-native-vector-icons` that does not uses the `react-native` `TabBarIOS` deprecated component.

### Back to the beginning?
With that solved, it becomes clear that now i'm facing a problem specific to this monorepo architecture, because the icons still will not render in any project:
![Screenshot from 2020-08-16 16-10-43](https://user-images.githubusercontent.com/38087682/90342096-e9b4e600-dfdb-11ea-9676-f6c029006cf0.png)

### Current Setup
#### > package/mobile/android/app/build.gradle
```gradle
//...
project.ext.react = [
        entryFile: "packages/mobile/index.js",
        root: "../../../../"
]
apply from: "../../../../node_modules/react-native/react.gradle"
project.ext.vectoricons = [
    iconFontNames: [ 'Ionicons.ttf' ]
]
apply from: "../../../../node_modules/@ovaeasy/react-native-vector-icons/fonts.gradle"
//...
```
#### > packages/[web,mobile,commons]/package.json
```json
  "dependencies": {
    "@ovaeasy/react-native-vector-icons": "^7.0.4"
```
#### > package.json (root)
```json
{
    "name": "proyectoSembrar",
    "private": true,
    "workspaces": {
        "packages": [
            "packages/*"
        ],
        "nohoist": []
    },
    "dependencies": {
        "commons": "0.0.1",
        "react-native": "0.63.2"
    }
}
```
#### > packages/web/config-overrides.js
```javascript
const appIncludes = [
  resolveApp('src'),
  resolveApp('../commons/src'),
  resolveApp('../commons/pages'),
  resolveApp('../../node_modules/@ovaeasy'),
  resolveApp('../../node_modules/@ovaeasy/react-native-vector-icons'),
]
```

@hosseinmd @brunolemos any ideas?

**Comment by hosseinmd** [comment]
Be sure react-native-vector-icons is installed on root node_module folder. If that is not there. Add that to both web and mobile packages.json

**Comment by Pra3t0r5** [comment]
@hosseinmd 
> Be sure react-native-vector-icons is installed on root node_module folder. If that is not there. Add that to both web and mobile packages.json

I'm not using RNVI anymore, i'm using a fork of it with greater compatibility for `react-native 0.63.x`, and it is present in the root `node_modules` folder:
```log
node_modules
└── @ovaeasy
    └── react-native-vector-icons
```
On a side note, i could alias it to solve any import route problem, but how? 
It would be solvable with a `.babelrc` somewhere, but this project uses webpack and rewire, i have no idea how to add this:
```js
alias: {
      'react-native-vector-icons': '@ovaeasy/react-native-vector-icons',
}
```

**Comment by brunolemos** [comment]
Check the source code of https://github.com/devhubapp/devhub, it's using react-native-vector-icons and react-native 0.63.

Important files:

- https://github.com/devhubapp/devhub/blob/ccc13ba1e91110f111fe9509efa84eadc3ef34a1/packages/mobile/android/settings.gradle#L6-L7
- https://github.com/devhubapp/devhub/blob/ccc13ba1e91110f111fe9509efa84eadc3ef34a1/packages/mobile/android/app/build.gradle#L89-L98
- https://github.com/devhubapp/devhub/blob/1e96cf2da050977e68bc3ae9c2b74d6fc4a441f2/packages/mobile/react-native.config.js#L8-L11
- https://github.com/devhubapp/devhub/tree/1e96cf2da050977e68bc3ae9c2b74d6fc4a441f2/packages/components/src/libs/vector-icons
- https://github.com/devhubapp/devhub/blob/1e96cf2da050977e68bc3ae9c2b74d6fc4a441f2/packages/web/config-overrides.js#L17
- https://github.com/devhubapp/devhub/blob/master/patches/react-native-vector-icons%2B6.6.0.patch

**Comment by Pra3t0r5** [comment]
@brunolemos thank you very much kind sir! I could solve most of the issues on my repo with these links. However, i do have one more question about this one:
> * https://github.com/devhubapp/devhub/tree/1e96cf2da050977e68bc3ae9c2b74d6fc4a441f2/packages/components/src/libs/vector-icons

I'm working on a js based project, can you explain me what it does and how to migrate it to js?

**Comment by toto1384** [comment]
I get this error when using react-native-vector-icons with a monorepo

```
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|       return (
>         <Text selectable={false} {...props}>
|           {glyph}
|           {children}
```
