### ISSUE TITLE
How to bring it to production?

### ISSUE THREAD

**Issue by annetyy** [brunolemos/react-native-web-monorepo#64]
How to bring it to production?
Get the APK and Web Server?

**Comment by hosseinmd** [comment]
### for android
mac:
`$
cd packages/mobile/android && ./gradlew assembleRelease
`
window:
`$
cd packages/mobile/android && gradlew assembleRelease
`
### for web
`$
yarn workspace web build
`

**Comment by nadjsyrb** [comment]
what about ios?

**Comment by annetyy** [comment]
thank you so much @hosseinmd !!!
works fine web/android :+1: 

i'll let this issue open cause i wanna know about mac/ios in the future

**Comment by brunolemos** [comment]
This repository doesn't cause any change on how you release an app to production.

For iOS, you need to open Xcode > Product > Archive and then upload it to App Store.
