### ISSUE TITLE
watchFolders don't resolve path of images from another package

### ISSUE THREAD

**Issue by hosseinmd** [brunolemos/react-native-web-monorepo#66]
I have an assets package for project images, after I Replace  watchFolders with projectRoot, images not showing.

**Comment by brunolemos** [comment]
Does it work with watchFolders or projectRoot? You can leave it the way it works

**Comment by hosseinmd** [comment]
It works with projectRoot. I think we should have a way to use watchFolders and still work images.

**Comment by brunolemos** [comment]
Have you tried setting both?

**Comment by hosseinmd** [comment]
> Have you tried setting both? Any particular reason to prefer watchFolders? I guess anything that works in your project should be fine

Your right, I will try both soon.

**Comment by brunolemos** [comment]
I just tried the code on master and it worked fine. Let me know if you managed it to work.

`import image from 'assets/image.jpg'`

`<Image source={image} style={{ width: '100%', height: 400 }} />`

**Comment by hosseinmd** [comment]
I changed this tow files, every things work know

metro.config.js
```js
module.exports = {
  projectRoot: path.resolve(__dirname, "../../"),
  watchFolders: [path.resolve(__dirname, "../../")],
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};
```

MainApplication.java
```java
        @Override
        protected String getJSMainModuleName() {
          return "packages/mobile/index";
        }
```
