### ISSUE TITLE
Support for experimental syntax

### ISSUE THREAD

**Issue by Secretmapper** [brunolemos/react-native-web-monorepo#7]
Great tutorial/repo!

I'm currently using an external library that seems to use classProperties (and I would probably be using it as well)

```
Support for the experimental syntax 'classProperties' isn't currently enabled (26:20):

export default class AgendaView extends Component {
> 26 |   static propTypes = {
```

Is there any workaround right now for these types of errors?

**Comment by brunolemos** [comment]
Thanks!

Ideally the external lib should have a es5 compatible code.
But if it doesn't have, you need to make create-react-app compile it.

Add the path to the node_modules package here: https://github.com/brunolemos/react-native-web-monorepo/blob/4129a89ba8e34d3ee326ce71cf9ea46adb4d047a/packages/web/config-overrides.js#L9

**Comment by iamraffe** [comment]
Does this mean doing: `const appIncludes = [ resolveApp('src'),  resolveApp('../components/src'), resolveApp('node_modules') ] `? Or should I reference a specific package?

**Comment by Secretmapper** [comment]
In my case I referenced the specific offending package
