### ISSUE TITLE
import/no-extraneous-dependencies

### ISSUE THREAD

**Issue by joae** [brunolemos/react-native-web-monorepo#73]
Hi!
Probably this is something I didn't understand. 
If I add a react-native lib in component workspace, autolink does not work.
Adding to mobile workspace autolink works well, but I'm getting lint error: import/no-extraneous-dependencies

My use case is I have an app with some charts and I want to add `victory` for web and `victory-native` for mobile.
Then I have `PieChart.tsx` and `PieChart.web.tsx`.

What is the best strategy to add a new dependency? What do you recommend in this case.

Thanks in advance!

**Comment by brunolemos** [comment]
you should add the dependencies to all packages that directly use them 

just make sure they have the exact same version, without `~` or `^`

**Comment by joae** [comment]
Thanks!
