### ISSUE TITLE
How to add react-native-maps and react-native-web-maps

### ISSUE THREAD

**Issue by ktprograms** [brunolemos/react-native-web-monorepo#81]
I saw in the [GitHub](https://github.com/react-native-web-community/react-native-web-maps) for react-native-web-maps that I need to alias `react-native-maps` to `react-native-web-maps`, but I'm not sure how for this template. Thanks!

**Comment by sendyputra** [comment]
```
  //react-native-web-maps
  config.resolve.alias = {
    ...(config.resolve.alias || {}),
    "react-native-maps$": "react-native-web-maps",
  };
```

put at config-overrides.js

**Comment by ktprograms** [comment]
Thanks!
