### ISSUE TITLE
README instructions not working for me?

### ISSUE THREAD

**Issue by iamraffe** [brunolemos/react-native-web-monorepo#9]
I'm trying to follow these instructions (CLI):

How to run

$ git clone git@github.com:brunolemos/react-native-web-monorepo.git
$ cd react-native-web-monorepo
$ yarn
$ yarn workspace mobile start

Run the project

Via CLI
Open a new terminal tab
$ cd packages/mobile
$ npm un -g react-native-cli
$ npm i -g @react-native-community/cli
$ react-native run-ios or react-native run-android

I get this:

![Screen Shot 2019-04-25 at 13 49 17](https://user-images.githubusercontent.com/11524607/56733723-40e8d480-6761-11e9-8145-f6f1b06e5ac3.png)

Any pointers as to why?

**Comment by brunolemos** [comment]
I was not able to reproduce. Were you able to run it?
My guess is that you'd need to follow the react-native installation docs: https://facebook.github.io/react-native/docs/getting-started.html#native
